from collections.abc import Awaitable, Callable, Mapping
from enum import StrEnum
from functools import partial
from pathlib import Path
import re
from typing import override

import anyio
import anyio.to_thread
from expression import Error, Ok, Result
from frozendict import frozendict
import msgspec
from watchfiles import awatch, Change, DefaultFilter

from admin.core import completed, Detail, Envelope, fault, Row, Status
from admin.runtime import async_boundary, BoundaryFault, Fact, guarded, Receipt, RetryClass, RuntimeRail, Signals, spawn
from admin.settings import MaghzSettings, McpServerSettings


# --- [TYPES] ---------------------------------------------------------------------------


class ServerKind(StrEnum):
    POSTGRES = "postgres"
    GOOGLE_WORKSPACE = "google-workspace"
    NOTEBOOKLM = "notebooklm"
    EXA = "exa"
    PERPLEXITY = "perplexity"
    TAVILY = "tavily"
    HOSTINGER = "hostinger"
    GITHUB = "github"
    CONTEXT7 = "context7"
    GREPTILE = "greptile"
    NUGET = "nuget"
    JUPYTER = "jupyter"
    DOPPLER_REMOTE = "doppler-remote"


class McpOp(StrEnum):
    GENERATE = "generate"
    VALIDATE = "validate"
    DIFF = "diff"
    WATCH = "watch"
    CONVERGE = "converge"


class ServerSpec(msgspec.Struct, frozen=True, gc=False):
    command: str = ""
    args: tuple[str, ...] = ()
    image: str = ""
    env: frozendict[str, str] = frozendict()
    docker_env: frozendict[str, str] = frozendict()
    http_url: str = ""
    http_headers: frozendict[str, str] = frozendict()

    @property
    def is_docker(self) -> bool:

        return bool(self.image)

    @property
    def is_http(self) -> bool:

        return bool(self.http_url)

    def argv(self, docker_overlay: Mapping[str, str] | None = None) -> list[str]:

        env = {**self.docker_env, **(docker_overlay or {})}
        flags = [token for key, value in env.items() for token in ("-e", f"{key}={value}")]
        return [*self.args, *flags, *([self.image] if self.image else [])]

    def environ(self, overlay: Mapping[str, str]) -> dict[str, str]:

        return {**self.env, **overlay}


class McpConfigDetail(Detail, frozen=True, tag="mcp"):
    op: McpOp
    artifacts: tuple[str, ...]
    server_count: int
    servers: tuple[ServerKind, ...]
    drift: tuple[str, ...] = ()
    result: str = ""


_REPO_ROOT = str(Path.cwd())
_PKG_DIR = str(Path(__file__).resolve().parent)
_WATCHED_INPUTS = {Path(".env"), Path("admin/mcp.py"), Path("admin/settings.py")}
_PLACEHOLDER = re.compile(r"\$\{MAGHZ_MCP__([A-Z0-9_]+)\}")
_MCP_JSON_PATH = ".mcp.json"
_CODEX_CONFIG_PATH = ".codex/config.toml"
_MCP_FIELDS = frozenset(McpServerSettings.model_fields)
_ENCODER = msgspec.json.Encoder()
_DECODER = msgspec.json.Decoder(type=dict[str, object])


class _RenderInputsFilter(DefaultFilter):
    @override
    def __call__(self, change: Change, path: str) -> bool:
        if not super().__call__(change, path):
            return False
        try:
            relative = Path(path).relative_to(_REPO_ROOT)
        except ValueError:
            return False
        return relative in _WATCHED_INPUTS


_WATCH_FILTER = _RenderInputsFilter()


def _render(cfg: MaghzSettings) -> dict[str, object]:

    servers: dict[str, object] = {}
    for kind in ServerKind:
        spec = _SERVER_TABLE[kind]
        overlay = _ENV_OVERLAY.get(kind)
        docker_overlay = _DOCKER_ENV_OVERLAY.get(kind)
        servers[kind.value] = (
            {"type": "http", "url": spec.http_url, "headers": dict(spec.http_headers)}
            if spec.is_http
            else {
                "command": spec.command,
                "args": spec.argv(docker_overlay(cfg) if docker_overlay else None),
                "env": spec.environ(overlay(cfg) if overlay else {}),
            }
        )
    return {"mcpServers": servers}


def _render_codex(cfg: MaghzSettings) -> str:
    lines = ["# Generated by `maghz mcp generate`; edit admin/mcp.py instead.", ""]
    for kind in ServerKind:
        lines.extend(_codex_server(kind, _SERVER_TABLE[kind], cfg))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _codex_server(kind: ServerKind, spec: ServerSpec, cfg: MaghzSettings) -> list[str]:
    header = [f"[mcp_servers.{_toml_key(kind.value)}]"]
    if spec.is_http:
        return _codex_http(header, spec)
    return _codex_process(header, kind, spec, cfg)


def _codex_http(header: list[str], spec: ServerSpec) -> list[str]:
    rows = [*header, f"url = {_toml_str(spec.http_url)}"]
    if bearer := _bearer_env(spec.http_headers):
        return [*rows, f"bearer_token_env_var = {_toml_str(bearer)}"]
    if headers := _env_headers(spec.http_headers):
        return [*rows, f"env_http_headers = {_toml_inline(headers)}"]
    return rows


def _codex_process(header: list[str], kind: ServerKind, spec: ServerSpec, cfg: MaghzSettings) -> list[str]:
    rows = [*header, f"command = {_toml_str(spec.command)}"]
    if spec.args:
        rows.append("args = " + _toml_array(spec.args))
    overlay = _ENV_OVERLAY.get(kind)
    env = spec.environ(overlay(cfg) if overlay else {})
    env_vars = tuple(name for value in env.values() if (name := _placeholder_name(value)))
    if env_vars:
        rows.append("env_vars = " + _toml_array(env_vars))
    return rows


def _toml_key(value: str) -> str:
    return value if re.fullmatch(r"[A-Za-z0-9_-]+", value) else _toml_str(value)


def _toml_str(value: str) -> str:
    return msgspec.json.encode(value).decode()


def _toml_array(values: tuple[str, ...]) -> str:
    return "[" + ", ".join(_toml_str(value) for value in values) + "]"


def _toml_inline(values: Mapping[str, str]) -> str:
    return "{ " + ", ".join(f"{_toml_str(key)} = {_toml_str(value)}" for key, value in values.items()) + " }"


def _placeholder_name(value: str) -> str | None:
    matched = re.fullmatch(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}", value)
    return matched.group(1) if matched else None


def _env_headers(headers: Mapping[str, str]) -> dict[str, str]:
    return {key: name for key, value in headers.items() if (name := _placeholder_name(value))}


def _bearer_env(headers: Mapping[str, str]) -> str | None:
    value = headers.get("Authorization")
    if value is None:
        return None
    matched = re.fullmatch(r"Bearer \$\{([A-Za-z_][A-Za-z0-9_]*)\}", value)
    return matched.group(1) if matched else None


async def _generate(cfg: MaghzSettings) -> RuntimeRail[McpConfigDetail]:

    payload = msgspec.json.format(_ENCODER.encode(_render(cfg)), indent=2)
    codex = _render_codex(cfg).encode()

    async def _write_all() -> None:
        await anyio.Path(_MCP_JSON_PATH).write_bytes(payload)
        await anyio.Path(_CODEX_CONFIG_PATH).parent.mkdir(parents=True, exist_ok=True)
        await anyio.Path(_CODEX_CONFIG_PATH).write_bytes(codex)

    written = await async_boundary("mcp.write", _write_all, catch=OSError)
    return written.map(lambda _bytes: _detail(McpOp.GENERATE))


async def _validate(_cfg: MaghzSettings) -> RuntimeRail[McpConfigDetail]:

    return (await _read_committed()).bind(lambda read: _coverage(read[0] + read[2].encode()))


def _coverage(raw: bytes) -> RuntimeRail[McpConfigDetail]:

    unbacked = frozenset(m.group(0) for m in _PLACEHOLDER.finditer(raw.decode(errors="replace")) if m.group(1).lower() not in _MCP_FIELDS)
    if unbacked:
        return Error(BoundaryFault(boundary=("mcp.validate", f"placeholders without a McpServerSettings field: {', '.join(sorted(unbacked))}")))
    return Ok(_detail(McpOp.VALIDATE))


async def _diff(cfg: MaghzSettings) -> RuntimeRail[McpConfigDetail]:

    rendered = msgspec.to_builtins(_render(cfg))["mcpServers"]
    codex = _render_codex(cfg)
    return (await _read_committed()).map(
        lambda read: _detail(McpOp.DIFF, drift=(*_drift(read[1], rendered), *(("codex-config",) if read[2] != codex else ())))
    )


def _drift(decoded: dict[str, object], rendered: object) -> tuple[str, ...]:

    committed = decoded.get("mcpServers")
    servers = committed if isinstance(committed, Mapping) else {}
    rows = rendered if isinstance(rendered, Mapping) else {}
    return tuple(kind.value for kind in ServerKind if servers.get(kind.value) != rows.get(kind.value))


async def _watch(cfg: MaghzSettings) -> RuntimeRail[McpConfigDetail]:

    if (initial := await _generate(cfg)).is_error():
        return initial
    async for batch in awatch(_REPO_ROOT, watch_filter=_WATCH_FILTER):
        facts: dict[str, object] = {"changes": [change.raw_str() for change, _ in batch], "count": len(batch)}
        await Signals.emit_async(Receipt.of("mcp", Fact("admitted", McpOp.WATCH.value, facts)))
        if (regen := await _generate(cfg)).is_error():
            return regen
    return Ok(_detail(McpOp.WATCH))


async def _converge(cfg: MaghzSettings) -> RuntimeRail[McpConfigDetail]:

    match await spawn(("docker", "--version"), subject="mcp.converge", retry_class=RetryClass.PROC):
        case Result(tag="error", error=probe_fault):
            return Error(probe_fault)
        case Result(ok=probe) if probe.returncode != 0:
            detail = probe.stderr.decode(errors="replace").strip() or f"exit {probe.returncode}"
            return Error(BoundaryFault(config=("mcp.converge", f"docker unavailable: {detail}")))
    return await _converge_images(cfg)


async def _converge_images(cfg: MaghzSettings) -> RuntimeRail[McpConfigDetail]:

    def _blocking() -> str:
        # The Automation API drives the host-side plugin stack; the import is gated here (dual-band law) so a
        # CONVERGE-free runtime core never pays the heavy load, and the `auto.Stack` type stays out of every
        # signature (a `TYPE_CHECKING`-only return annotation would crash the beartype claw's forward-ref eval).
        from pulumi import automation as auto  # noqa: PLC0415

        state = (cfg.infra.state_dir / "mcp").resolve()
        state.mkdir(parents=True, exist_ok=True)  # the file:// backend cannot open a bucket whose directory does not exist
        opts = auto.LocalWorkspaceOptions(
            project_settings=auto.ProjectSettings(name="maghz-mcp", runtime="python", backend=auto.ProjectBackend(url=f"file://{state}")),
            # Pin the Colima socket and neutralize the leaked machine DOCKER_CERT_PATH/DOCKER_TLS_VERIFY (which
            # would point the docker provider at a nonexistent TLS cert dir), matching the infra runner setup.
            env_vars={"PULUMI_CONFIG_PASSPHRASE": "", "DOCKER_HOST": cfg.infra.docker_host, "DOCKER_CERT_PATH": "", "DOCKER_TLS_VERIFY": ""},
        )
        stack = auto.create_or_select_stack(stack_name="images", project_name="maghz-mcp", program=partial(_define_images, cfg), opts=opts)
        return stack.up(on_output=lambda _line: None).summary.result  # select-or-create and `up` both run in the worker thread

    rail = await guarded(RetryClass.PROC, lambda: anyio.to_thread.run_sync(_blocking), subject="mcp.converge")
    return rail.map(lambda result: _detail(McpOp.CONVERGE, result=result))


def _define_images(cfg: MaghzSettings) -> None:

    import pulumi  # noqa: PLC0415 - dual-band: heavy host-side plugin stack, imported only inside the offloaded program
    import pulumi_docker as docker  # noqa: PLC0415

    provider = docker.Provider("colima", host=cfg.infra.docker_host)
    on = pulumi.ResourceOptions(provider=provider)
    for kind in ServerKind:
        spec = _SERVER_TABLE[kind]
        if spec.is_docker:
            image = docker.RemoteImage(f"mcp-{kind.value}", name=spec.image, keep_locally=True, opts=on)
            pulumi.export(f"{kind.value}_image", image.repo_digest)


async def _read_committed() -> RuntimeRail[tuple[bytes, dict[str, object], str]]:

    async def _read_decode() -> tuple[bytes, dict[str, object], str]:
        raw = await anyio.Path(_MCP_JSON_PATH).read_bytes()
        codex = await anyio.Path(_CODEX_CONFIG_PATH).read_text()
        return raw, _DECODER.decode(raw), codex

    return await async_boundary("mcp.validate", _read_decode, catch=(OSError, msgspec.DecodeError))


def _detail(op: McpOp, *, drift: tuple[str, ...] = (), result: str = "") -> McpConfigDetail:

    servers = tuple(ServerKind)
    return McpConfigDetail(
        op=op, artifacts=(_MCP_JSON_PATH, _CODEX_CONFIG_PATH), server_count=len(servers), servers=servers, drift=drift, result=result
    )


def _workspace_overlay(cfg: MaghzSettings) -> dict[str, str]:

    redirect = str(cfg.integrations.workspace_oauth_redirect_uri or "")
    return {"WORKSPACE_MCP_CREDENTIALS_DIR": "${WORKSPACE_MCP_CREDENTIALS_DIR}", **({"GOOGLE_OAUTH_REDIRECT_URI": redirect} if redirect else {})}


_SERVER_TABLE: frozendict[ServerKind, ServerSpec] = frozendict({
    ServerKind.POSTGRES: ServerSpec(
        # The Forge launcher owns the whole spawn contract — uvx Python pin, DSN mapping from
        # MAGHZ_MCP__DATABASE_URI, launchd GUI replay fallback, and the loud exit 78 on an unset DSN — so both
        # client artifacts converge on one command instead of re-encoding an inline uvx line.
        command="forge-maghz-postgres-mcp",
        env=frozendict({"MAGHZ_MCP__DATABASE_URI": "${MAGHZ_MCP__DATABASE_URI}"}),
    ),
    ServerKind.GOOGLE_WORKSPACE: ServerSpec(
        command="forge-workspace-mcp",
        args=("--tool-tier", "extended"),
        env=frozendict({"GOOGLE_OAUTH_CLIENT_ID": "${GOOGLE_OAUTH_CLIENT_ID}", "GOOGLE_OAUTH_CLIENT_SECRET": "${GOOGLE_OAUTH_CLIENT_SECRET}"}),
    ),
    ServerKind.NOTEBOOKLM: ServerSpec(command="notebooklm-mcp"),
    ServerKind.EXA: ServerSpec(
        http_url="https://mcp.exa.ai/mcp?tools=web_search_exa,web_fetch_exa,web_search_advanced_exa,agent_tools",
        http_headers=frozendict({"x-api-key": "${EXA_API_KEY}"}),
    ),
    # Forge-owned launchers pin these servers by version and warm-start from an
    # XDG cache — no per-spawn npx registry resolution, no npm on any PATH.
    ServerKind.PERPLEXITY: ServerSpec(command="forge-perplexity-mcp", env=frozendict({"PERPLEXITY_API_KEY": "${PERPLEXITY_API_KEY}"})),
    ServerKind.TAVILY: ServerSpec(command="forge-tavily-mcp", env=frozendict({"TAVILY_API_KEY": "${TAVILY_API_KEY}"})),
    ServerKind.HOSTINGER: ServerSpec(command="forge-hostinger-mcp", env=frozendict({"HOSTINGER_API_TOKEN": "${HOSTINGER_API_TOKEN}"})),
    ServerKind.GITHUB: ServerSpec(
        http_url="https://api.githubcopilot.com/mcp/", http_headers=frozendict({"Authorization": "Bearer ${GH_PROJECTS_TOKEN}"})
    ),
    ServerKind.CONTEXT7: ServerSpec(http_url="https://mcp.context7.com/mcp", http_headers=frozendict({"CONTEXT7_API_KEY": "${CONTEXT7_API_KEY}"})),
    # HTTP code-review remote: whole-repo semantic review over the indexed codebase. Bears the bare
    # `${GREPTILE_API_KEY}` the env bootstrap forwards (the github/context7 placeholder shape), so it backs no
    # `McpServerSettings` field and resolves at the `op run -- claude` boundary.
    ServerKind.GREPTILE: ServerSpec(
        http_url="https://api.greptile.com/mcp", http_headers=frozendict({"Authorization": "Bearer ${GREPTILE_API_KEY}"})
    ),
    # Host-process package-intelligence server: the Forge-provided `nuget-mcp` launcher runs NuGet.Mcp.Server
    # via `dotnet tool exec` (the launcher fixes DOTNET_ROOT for the .NET 10 apphost). No secret, no image, no
    # http — a bare command like NOTEBOOKLM. Carried for parity wherever a session has the .NET 10 SDK; inert
    # where the `nuget-mcp` launcher is absent (e.g. the Postgres-only VPS), which an MCP client tolerates.
    ServerKind.NUGET: ServerSpec(command="nuget-mcp"),
    ServerKind.JUPYTER: ServerSpec(command="forge-jupyter-mcp"),
    # VPS-custody Doppler MCP: stdio rides ssh into the prd host's warm `maghz-mcp` container. The
    # /srv/maghz scope token resolves remotely inside the ssh leg and enters the container as env —
    # the token never exists client-side. Read-only, project/config pinned; the token is the boundary.
    ServerKind.DOPPLER_REMOTE: ServerSpec(
        command="ssh",
        args=(
            "maghz",
            (
                'DOPPLER_TOKEN="$(doppler configure get token --plain --scope /srv/maghz)"'
                " docker exec -i -e DOPPLER_TOKEN maghz-mcp"
                " /opt/mcp/bin/doppler-mcp --read-only --project maghz --config prd_host"
            ),
        ),
    ),
})


_ENV_OVERLAY: frozendict[ServerKind, Callable[[MaghzSettings], dict[str, str]]] = frozendict({ServerKind.GOOGLE_WORKSPACE: _workspace_overlay})
_DOCKER_ENV_OVERLAY: frozendict[ServerKind, Callable[[MaghzSettings], dict[str, str]]] = frozendict()
_BUILD: frozendict[McpOp, Callable[[MaghzSettings], Awaitable[RuntimeRail[McpConfigDetail]]]] = frozendict({
    McpOp.GENERATE: _generate,
    McpOp.VALIDATE: _validate,
    McpOp.DIFF: _diff,
    McpOp.WATCH: _watch,
    McpOp.CONVERGE: _converge,
})


async def mcp(op: McpOp, cfg: MaghzSettings) -> Envelope:

    match await _BUILD[op](cfg):
        case Result(tag="ok", ok=detail):
            drifted = frozenset(detail.drift)
            rows = tuple(Row(key=kind.value, text="drift" if kind.value in drifted else "ok") for kind in ServerKind)
            return completed(Status.FAILED if drifted else Status.OK, detail, rows=rows)
        case Result(error=boundary_fault):
            return fault(boundary_fault.headline(), {key: str(value) for key, value in boundary_fault.facts().items()})


__all__ = ["McpConfigDetail", "McpOp", "ServerKind", "ServerSpec", "mcp"]
